# create and drop tables and sequences, loads import.sql
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    project.user.UserClient: DEBUG
  profiles:
    active: production

management:
  server:
    port: 8443

server:
  port: ${PORT:5000}
  ssl:
    key-store: keystore.p12
    key-store-password: mpintegration
    keyStoreType: PKCS12
    keyAlias: tomcat
zk:
  springboot-packaging: war
  homepage:

mp:
  integratorId: dev_24c65fb163bf11ea96500242ac130004
  webhook: https://eutopiaespacio.com.ar/mphook
  testSeller:
    collectorId: 469485398
    publicKey: APP_USR-7eb0138a-189f-4bec-87d1-c0504ead5626
    accessToken: APP_USR-6317427424180639-042414-47e969706991d3a442922b0702a0da44-469485398
  buyer:
    id: 471923173
    email: test_user_63274575@testuser.com
    password: qatest2417
    name: Lalo
    surname: Landa
    areaCode: 11
    telephone: 22223333
    streetName: False
    streetNumber: 123
    postalCode: 1111
